# Generated by Django 5.1.1 on 2024-10-23 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_image_blog_image1_blog_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image2',
        ),
    ]
