# Generated by Django 5.1.1 on 2024-10-23 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_image2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image1',
            new_name='image',
        ),
    ]
