# Generated by Django 5.1.1 on 2024-10-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=202)),
                ('title', models.CharField(max_length=202)),
                ('image', models.ImageField(upload_to='about/')),
                ('description', models.TextField()),
                ('twitter', models.CharField(default='not_available', max_length=202)),
                ('facebook', models.CharField(max_length=202)),
                ('instagram', models.CharField(max_length=202)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=202)),
                ('numbers', models.IntegerField()),
            ],
        ),
    ]
